name: E2E Tests

on:
  pull_request:

concurrency:
  group: e2e-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check_paths:
    runs-on: ubuntu-latest

    outputs:
      should_run: ${{ steps.filter.outputs.e2e }}
      
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            e2e:
              - 'kubernetes/**'
              - 'src/backend/**'
              - 'src/frontend/**'
              - '.github/workflows/e2e-tests.yaml'

  wait_for_tests:
    name: Wait for Unit Tests
    needs: check_paths
    if: ${{ needs.check_paths.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Backend Tests
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.head_ref }}
          check-name: 'Test Backend'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped

      - name: Wait for Frontend Tests
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.head_ref }}
          check-name: 'Test Frontend'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped

  test:
    name: Test E2E
    needs: [check_paths, wait_for_tests]
    if: ${{ needs.check_paths.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      KUBECONFIG: ${{ github.workspace }}/.kube/config
    defaults:
      run:
        working-directory: ./kubernetes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install k3d
        uses: rinx/setup-k3d@v0.0.2

      - name: Override KUBECONFIG
        run: |
          mkdir -p ${{ github.workspace }}/.kube
          echo "KUBECONFIG=${{ github.workspace }}/.kube/config" >> $GITHUB_ENV

      - name: Set up Python 3.13
        run: uv python install 3.13

      - name: Install dependencies
        run: |
          uv sync --locked --dev

      - name: Lint with Ruff
        run: |
          uv run ruff check --output-format=github --target-version=py313 e2e_test.py
          uv run ruff format --diff --check --target-version=py313 e2e_test.py

      - name: Run E2E tests
        run: |
          uv run e2e_test.py

      - name: Cleanup k3d cluster
        if: always()
        run: k3d cluster delete study-app-cluster || true
